
version: '3'

services:
  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_PASSWORD: ""
    ports:
      - "5432:5432"
    volumes:
      - /home/user
    networks:
      - postgres-compose-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ""
      PGADMIN_DEFAULT_PASSWORD: ""
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
